import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";

import { NavBar } from "./components/NavBar";
import { Footer } from "./components/Footer";

const poppins = Poppins({ weight: ['500'], preload: false});

export const metadata: Metadata = {
  title:{
    default: 'Job Finder',
    template: '%s | Job Finder'
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={poppins.className}>
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
